language: node_js

node_js:
  - "6"

before_install:
  - npm install -g qunit

script:
  - npm run lint
  - qunit

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy-to-gh-pages.sh $TRAVIS_BRANCH
  on:
    all_branches: true
